<!DOCTYPE html>
 
<html lang="es">
    <head>
        <meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="shortcut icon" href="45.jpg">    
        <title>CONJUNTO RESIDENCIAL SANTA SOFIA</title> 
<link rel="stylesheet" href="css/index.css" type="text/css" />
        </head>
    <body>
      <form>
<center><img src=45.jpg><img src="nit.jpg"></center>
<input type="text"max-length="20"placeholder="TITULO DEL MENSAJE">
<input type="text"max-length="20"placeholder="ID/CODIGO" required>
<input type="text"max-length="20"placeholder="URL IMAGEN">
<h2>INFORMACION DEL ANUNCIO</h2>
<textarea type="text"max-length="20"placeholder="MENSAJE ANUNCIO"></textarea>
 <input type="date"max-length="20"placeholder="FECHA INICIO DEL ANUNCIO">
 <input type="date"max-length="20"placeholder="FECHA FIN DEL ANUNCIO">
<input type="text"max-length="20"placeholder="DESTINATARIO">

<center>
<button type="button">CREAR </button>
    <button type="button">MODIFICAR </button>
    <button type="button">INHABILITAR </button></center>
      </form>
        <div class="button">
           <button type="button"><a href="menu-1.php">ATRAS</a></button>
        </div>
        <footer class="footer">
        <img src="https://img.icons8.com/dusk/48/000000/gmail.png"><p>santasofiasur1@hotmail.com</p>
        <img src="https://img.icons8.com/color/48/000000/pittsburgh-map.png"><p>Cll 42 sur #12-55</p>
        <p class="copy">&copy; CONJUNTO RESIDENCIAL SANTA SOFIA I ETAPA </p>
    </footer>
          </body>
</html>